import { createFileRoute } from "@tanstack/react-router";
import { PageHero } from "@/components/page-hero";
import { SponsorInquiryForm } from "@/components/inquiry-form";

export const Route = createFileRoute("/sponsors")({
  head: () => ({
    meta: [
      { title: "Sponsors — Where brands buy attention | BKL Sharks" },
      { name: "description", content: "Title, Circuit, Round and Founder-Grant sponsorship packages for BKL Sharks. 4.2M live concurrents on JioCinema." },
      { property: "og:title", content: "Sponsors — BKL Sharks" },
      { property: "og:description", content: "Sponsorship packages with founder, audience and creator reach." },
    ],
  }),
  component: SponsorsPage,
});

const PACKAGES = [
  { tier: "T1", name: "Title Sponsor", scope: "Season-long brand presence. Stage naming rights. Post-show editorial.", price: "₹18 Cr+", units: "1 slot", color: "text-[var(--crimson)]" },
  { tier: "T2", name: "Circuit Sponsor", scope: "On-floor branding, audience badges, lobby activation, panel mention.", price: "₹5.5 Cr", units: "4 slots", color: "text-[var(--gold)]" },
  { tier: "T3", name: "Round Sponsor", scope: "Pre-roll, mid-show segment, founder-room branding for one round.", price: "₹1.6 Cr", units: "16 slots · 11 sold", color: "text-foreground" },
  { tier: "T4", name: "Founder Grant", scope: "Fund a non-dilutive ₹50 L stipend granted live on stage in your brand name.", price: "₹1.1 Cr", units: "8 slots", color: "text-[var(--gold)]" },
  { tier: "T5", name: "Community Partner", scope: "Creator network co-branding · meme-wall placement across the season.", price: "₹40 L", units: "Open", color: "text-muted-foreground" },
];

const METRICS: [string, string][] = [
  ["4.2M", "Avg live concurrents · JioCinema"],
  ["62M", "Short-form impressions / round"],
  ["83%", "Audience age 22–38 · builder index"],
  ["1,200+", "Founders in waitlist pipeline"],
  ["₹47 Cr", "Capital deployed live on stage S01"],
  ["41M", "Reels generated by S01"],
];

const PARTNERS = ["JioCinema", "Peak XV", "Razorpay", "Zomato", "Mahindra", "ICICI", "Tata Cliq", "BoAt", "Boult", "GoMechanic", "CRED", "Swiggy"];

const AUDIENCE = [
  { label: "22–28", value: 38 },
  { label: "29–35", value: 31 },
  { label: "36–45", value: 19 },
  { label: "46+", value: 12 },
];

const GEO = [
  ["Mumbai", 28], ["Bengaluru", 22], ["Delhi NCR", 17], ["Hyderabad", 9], ["Pune", 7], ["Chennai", 5], ["Tier-2+", 12],
];

function SponsorsPage() {
  return (
    <>
      <PageHero
        eyebrow="For Brands & Operators"
        title={<>Where brands <span className="italic text-[var(--gold)]/80">buy attention.</span></>}
        lede="BKL Sharks is the highest-pressure surface in India to put your brand in front of founders, operators, investors and the audience that decides what India builds next."
      />

      {/* METRICS */}
      <section className="py-16 px-6 border-b border-border">
        <div className="mx-auto max-w-7xl grid grid-cols-2 md:grid-cols-3 gap-px bg-border">
          {METRICS.map(([k, v]) => (
            <div key={v} className="bg-background p-8">
              <div className="font-display text-5xl mb-3 text-[var(--gold)]">{k}</div>
              <div className="font-mono text-[10px] uppercase tracking-[0.25em] text-muted-foreground leading-relaxed">{v}</div>
            </div>
          ))}
        </div>
      </section>

      {/* AUDIENCE BREAKDOWN */}
      <section className="py-20 px-6 border-b border-border">
        <div className="mx-auto max-w-7xl grid grid-cols-1 md:grid-cols-2 gap-16">
          <div>
            <span className="font-mono text-[10px] uppercase tracking-[0.4em] text-[var(--crimson)] mb-3 block">Audience · Telemetry</span>
            <h2 className="font-display text-3xl md:text-4xl mb-10">Builders, operators and angels in one room.</h2>
            <ul className="space-y-5">
              {AUDIENCE.map((a) => (
                <li key={a.label} className="grid grid-cols-12 gap-4 items-center">
                  <span className="col-span-2 font-mono text-xs">{a.label}</span>
                  <div className="col-span-9 h-2 bg-[var(--surface)] ring-1 ring-border overflow-hidden">
                    <div className="h-full bg-gradient-to-r from-[var(--crimson)] to-[var(--gold)]" style={{ width: `${a.value * 2}%` }} />
                  </div>
                  <span className="col-span-1 text-right font-mono text-xs">{a.value}%</span>
                </li>
              ))}
            </ul>
          </div>
          <div>
            <span className="font-mono text-[10px] uppercase tracking-[0.4em] text-[var(--gold)] mb-3 block">Geography · % of viewers</span>
            <h2 className="font-display text-3xl md:text-4xl mb-10">India's metro + tier-2 builders.</h2>
            <ul className="grid grid-cols-2 gap-px bg-border ring-1 ring-border">
              {GEO.map(([city, pct]) => (
                <li key={city as string} className="bg-background p-5">
                  <div className="font-mono text-[10px] uppercase tracking-[0.3em] text-muted-foreground mb-1">{city}</div>
                  <div className="font-display text-2xl">{pct}%</div>
                </li>
              ))}
            </ul>
          </div>
        </div>
      </section>

      {/* PACKAGES */}
      <section className="py-24 px-6 border-b border-border">
        <div className="mx-auto max-w-6xl">
          <h2 className="font-display text-4xl md:text-5xl mb-12">Sponsorship packages · S02</h2>
          <ul className="divide-y divide-border border-y border-border">
            {PACKAGES.map((p) => (
              <li key={p.name} className="grid grid-cols-12 gap-6 py-8 group hover:bg-[var(--surface)] px-6 -mx-6 transition-colors">
                <div className="col-span-12 md:col-span-1 font-mono text-xs tracking-[0.25em] text-muted-foreground">{p.tier}</div>
                <div className="col-span-12 md:col-span-3">
                  <h3 className={`font-display text-2xl ${p.color}`}>{p.name}</h3>
                  <div className="font-mono text-[10px] uppercase tracking-[0.25em] text-muted-foreground mt-1">{p.units}</div>
                </div>
                <p className="col-span-12 md:col-span-6 text-muted-foreground leading-relaxed">{p.scope}</p>
                <div className="col-span-12 md:col-span-2 md:text-right font-mono text-lg text-[var(--gold)]">{p.price}</div>
              </li>
            ))}
          </ul>
        </div>
      </section>

      {/* PARTNERS WALL */}
      <section className="py-20 px-6 border-b border-border">
        <div className="mx-auto max-w-7xl">
          <div className="flex items-end justify-between mb-10 flex-wrap gap-4">
            <h2 className="font-display text-3xl md:text-4xl">Brands who showed up to S01</h2>
            <span className="font-mono text-[10px] uppercase tracking-[0.3em] text-muted-foreground">Renewals open · S02</span>
          </div>
          <div className="grid grid-cols-2 md:grid-cols-4 lg:grid-cols-6 gap-px bg-border">
            {PARTNERS.map((p) => (
              <div key={p} className="bg-background h-24 flex items-center justify-center hover:bg-[var(--surface)] transition-colors">
                <span className="font-display text-xl text-muted-foreground hover:text-foreground transition-colors">{p}</span>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* INQUIRY FORM */}
      <section className="py-24 px-6">
        <div className="mx-auto max-w-3xl">
          <h2 className="font-display text-4xl md:text-5xl mb-2">Request the deck.</h2>
          <p className="text-muted-foreground mb-12">We respond within 48 hours with the S02 sponsorship deck, package availability and rate-card.</p>
          <SponsorInquiryForm />
        </div>
      </section>
    </>
  );
}