/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as SponsorsRouteImport } from './routes/sponsors'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PressKitRouteImport } from './routes/press-kit'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as PanelistsRouteImport } from './routes/panelists'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as JoinRouteImport } from './routes/join'
import { Route as InvitePanelistRouteImport } from './routes/invite-panelist'
import { Route as FoundersRouteImport } from './routes/founders'
import { Route as EpisodesRouteImport } from './routes/episodes'
import { Route as CreatorsRouteImport } from './routes/creators'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PanelistsSlugRouteImport } from './routes/panelists.$slug'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as LegalRefundsRouteImport } from './routes/legal.refunds'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as FoundersSlugRouteImport } from './routes/founders.$slug'
import { Route as EpisodesSlugRouteImport } from './routes/episodes.$slug'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTicketsRouteImport } from './routes/admin.tickets'
import { Route as AdminSponsorsRouteImport } from './routes/admin.sponsors'
import { Route as AdminSponsorContentRouteImport } from './routes/admin.sponsor-content'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminPostsRouteImport } from './routes/admin.posts'
import { Route as AdminPanelistsRouteImport } from './routes/admin.panelists'
import { Route as AdminInvitationsRouteImport } from './routes/admin.invitations'
import { Route as AdminFoundersRouteImport } from './routes/admin.founders'
import { Route as AdminEpisodesRouteImport } from './routes/admin.episodes'
import { Route as AdminApplicationsRouteImport } from './routes/admin.applications'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'

const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorsRoute = SponsorsRouteImport.update({
  id: '/sponsors',
  path: '/sponsors',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PressKitRoute = PressKitRouteImport.update({
  id: '/press-kit',
  path: '/press-kit',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelistsRoute = PanelistsRouteImport.update({
  id: '/panelists',
  path: '/panelists',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitePanelistRoute = InvitePanelistRouteImport.update({
  id: '/invite-panelist',
  path: '/invite-panelist',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundersRoute = FoundersRouteImport.update({
  id: '/founders',
  path: '/founders',
  getParentRoute: () => rootRouteImport,
} as any)
const EpisodesRoute = EpisodesRouteImport.update({
  id: '/episodes',
  path: '/episodes',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorsRoute = CreatorsRouteImport.update({
  id: '/creators',
  path: '/creators',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PanelistsSlugRoute = PanelistsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PanelistsRoute,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => LegalRoute,
} as any)
const LegalRefundsRoute = LegalRefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => LegalRoute,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LegalRoute,
} as any)
const FoundersSlugRoute = FoundersSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => FoundersRoute,
} as any)
const EpisodesSlugRoute = EpisodesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => EpisodesRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTicketsRoute = AdminTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSponsorsRoute = AdminSponsorsRouteImport.update({
  id: '/sponsors',
  path: '/sponsors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSponsorContentRoute = AdminSponsorContentRouteImport.update({
  id: '/sponsor-content',
  path: '/sponsor-content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPostsRoute = AdminPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPanelistsRoute = AdminPanelistsRouteImport.update({
  id: '/panelists',
  path: '/panelists',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInvitationsRoute = AdminInvitationsRouteImport.update({
  id: '/invitations',
  path: '/invitations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFoundersRoute = AdminFoundersRouteImport.update({
  id: '/founders',
  path: '/founders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEpisodesRoute = AdminEpisodesRouteImport.update({
  id: '/episodes',
  path: '/episodes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApplicationsRoute = AdminApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/apply': typeof ApplyRoute
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRoute
  '/creators': typeof CreatorsRoute
  '/episodes': typeof EpisodesRouteWithChildren
  '/founders': typeof FoundersRouteWithChildren
  '/invite-panelist': typeof InvitePanelistRoute
  '/join': typeof JoinRoute
  '/legal': typeof LegalRouteWithChildren
  '/panelists': typeof PanelistsRouteWithChildren
  '/partners': typeof PartnersRoute
  '/press-kit': typeof PressKitRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sponsors': typeof SponsorsRoute
  '/tickets': typeof TicketsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/episodes': typeof AdminEpisodesRoute
  '/admin/founders': typeof AdminFoundersRoute
  '/admin/invitations': typeof AdminInvitationsRoute
  '/admin/panelists': typeof AdminPanelistsRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sponsor-content': typeof AdminSponsorContentRoute
  '/admin/sponsors': typeof AdminSponsorsRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/admin/users': typeof AdminUsersRoute
  '/episodes/$slug': typeof EpisodesSlugRoute
  '/founders/$slug': typeof FoundersSlugRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refunds': typeof LegalRefundsRoute
  '/legal/terms': typeof LegalTermsRoute
  '/panelists/$slug': typeof PanelistsSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRoute
  '/creators': typeof CreatorsRoute
  '/episodes': typeof EpisodesRouteWithChildren
  '/founders': typeof FoundersRouteWithChildren
  '/invite-panelist': typeof InvitePanelistRoute
  '/join': typeof JoinRoute
  '/legal': typeof LegalRouteWithChildren
  '/panelists': typeof PanelistsRouteWithChildren
  '/partners': typeof PartnersRoute
  '/press-kit': typeof PressKitRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sponsors': typeof SponsorsRoute
  '/tickets': typeof TicketsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/episodes': typeof AdminEpisodesRoute
  '/admin/founders': typeof AdminFoundersRoute
  '/admin/invitations': typeof AdminInvitationsRoute
  '/admin/panelists': typeof AdminPanelistsRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sponsor-content': typeof AdminSponsorContentRoute
  '/admin/sponsors': typeof AdminSponsorsRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/admin/users': typeof AdminUsersRoute
  '/episodes/$slug': typeof EpisodesSlugRoute
  '/founders/$slug': typeof FoundersSlugRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refunds': typeof LegalRefundsRoute
  '/legal/terms': typeof LegalTermsRoute
  '/panelists/$slug': typeof PanelistsSlugRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/apply': typeof ApplyRoute
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRoute
  '/creators': typeof CreatorsRoute
  '/episodes': typeof EpisodesRouteWithChildren
  '/founders': typeof FoundersRouteWithChildren
  '/invite-panelist': typeof InvitePanelistRoute
  '/join': typeof JoinRoute
  '/legal': typeof LegalRouteWithChildren
  '/panelists': typeof PanelistsRouteWithChildren
  '/partners': typeof PartnersRoute
  '/press-kit': typeof PressKitRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sponsors': typeof SponsorsRoute
  '/tickets': typeof TicketsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/episodes': typeof AdminEpisodesRoute
  '/admin/founders': typeof AdminFoundersRoute
  '/admin/invitations': typeof AdminInvitationsRoute
  '/admin/panelists': typeof AdminPanelistsRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sponsor-content': typeof AdminSponsorContentRoute
  '/admin/sponsors': typeof AdminSponsorsRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/admin/users': typeof AdminUsersRoute
  '/episodes/$slug': typeof EpisodesSlugRoute
  '/founders/$slug': typeof FoundersSlugRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refunds': typeof LegalRefundsRoute
  '/legal/terms': typeof LegalTermsRoute
  '/panelists/$slug': typeof PanelistsSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/apply'
    | '/auth'
    | '/community'
    | '/creators'
    | '/episodes'
    | '/founders'
    | '/invite-panelist'
    | '/join'
    | '/legal'
    | '/panelists'
    | '/partners'
    | '/press-kit'
    | '/sitemap.xml'
    | '/sponsors'
    | '/tickets'
    | '/admin/analytics'
    | '/admin/applications'
    | '/admin/episodes'
    | '/admin/founders'
    | '/admin/invitations'
    | '/admin/panelists'
    | '/admin/posts'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/sponsor-content'
    | '/admin/sponsors'
    | '/admin/tickets'
    | '/admin/users'
    | '/episodes/$slug'
    | '/founders/$slug'
    | '/legal/privacy'
    | '/legal/refunds'
    | '/legal/terms'
    | '/panelists/$slug'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apply'
    | '/auth'
    | '/community'
    | '/creators'
    | '/episodes'
    | '/founders'
    | '/invite-panelist'
    | '/join'
    | '/legal'
    | '/panelists'
    | '/partners'
    | '/press-kit'
    | '/sitemap.xml'
    | '/sponsors'
    | '/tickets'
    | '/admin/analytics'
    | '/admin/applications'
    | '/admin/episodes'
    | '/admin/founders'
    | '/admin/invitations'
    | '/admin/panelists'
    | '/admin/posts'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/sponsor-content'
    | '/admin/sponsors'
    | '/admin/tickets'
    | '/admin/users'
    | '/episodes/$slug'
    | '/founders/$slug'
    | '/legal/privacy'
    | '/legal/refunds'
    | '/legal/terms'
    | '/panelists/$slug'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/apply'
    | '/auth'
    | '/community'
    | '/creators'
    | '/episodes'
    | '/founders'
    | '/invite-panelist'
    | '/join'
    | '/legal'
    | '/panelists'
    | '/partners'
    | '/press-kit'
    | '/sitemap.xml'
    | '/sponsors'
    | '/tickets'
    | '/admin/analytics'
    | '/admin/applications'
    | '/admin/episodes'
    | '/admin/founders'
    | '/admin/invitations'
    | '/admin/panelists'
    | '/admin/posts'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/sponsor-content'
    | '/admin/sponsors'
    | '/admin/tickets'
    | '/admin/users'
    | '/episodes/$slug'
    | '/founders/$slug'
    | '/legal/privacy'
    | '/legal/refunds'
    | '/legal/terms'
    | '/panelists/$slug'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ApplyRoute: typeof ApplyRoute
  AuthRoute: typeof AuthRoute
  CommunityRoute: typeof CommunityRoute
  CreatorsRoute: typeof CreatorsRoute
  EpisodesRoute: typeof EpisodesRouteWithChildren
  FoundersRoute: typeof FoundersRouteWithChildren
  InvitePanelistRoute: typeof InvitePanelistRoute
  JoinRoute: typeof JoinRoute
  LegalRoute: typeof LegalRouteWithChildren
  PanelistsRoute: typeof PanelistsRouteWithChildren
  PartnersRoute: typeof PartnersRoute
  PressKitRoute: typeof PressKitRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SponsorsRoute: typeof SponsorsRoute
  TicketsRoute: typeof TicketsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsors': {
      id: '/sponsors'
      path: '/sponsors'
      fullPath: '/sponsors'
      preLoaderRoute: typeof SponsorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/press-kit': {
      id: '/press-kit'
      path: '/press-kit'
      fullPath: '/press-kit'
      preLoaderRoute: typeof PressKitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panelists': {
      id: '/panelists'
      path: '/panelists'
      fullPath: '/panelists'
      preLoaderRoute: typeof PanelistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite-panelist': {
      id: '/invite-panelist'
      path: '/invite-panelist'
      fullPath: '/invite-panelist'
      preLoaderRoute: typeof InvitePanelistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founders': {
      id: '/founders'
      path: '/founders'
      fullPath: '/founders'
      preLoaderRoute: typeof FoundersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/episodes': {
      id: '/episodes'
      path: '/episodes'
      fullPath: '/episodes'
      preLoaderRoute: typeof EpisodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creators': {
      id: '/creators'
      path: '/creators'
      fullPath: '/creators'
      preLoaderRoute: typeof CreatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/panelists/$slug': {
      id: '/panelists/$slug'
      path: '/$slug'
      fullPath: '/panelists/$slug'
      preLoaderRoute: typeof PanelistsSlugRouteImport
      parentRoute: typeof PanelistsRoute
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/refunds': {
      id: '/legal/refunds'
      path: '/refunds'
      fullPath: '/legal/refunds'
      preLoaderRoute: typeof LegalRefundsRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof LegalRoute
    }
    '/founders/$slug': {
      id: '/founders/$slug'
      path: '/$slug'
      fullPath: '/founders/$slug'
      preLoaderRoute: typeof FoundersSlugRouteImport
      parentRoute: typeof FoundersRoute
    }
    '/episodes/$slug': {
      id: '/episodes/$slug'
      path: '/$slug'
      fullPath: '/episodes/$slug'
      preLoaderRoute: typeof EpisodesSlugRouteImport
      parentRoute: typeof EpisodesRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tickets': {
      id: '/admin/tickets'
      path: '/tickets'
      fullPath: '/admin/tickets'
      preLoaderRoute: typeof AdminTicketsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sponsors': {
      id: '/admin/sponsors'
      path: '/sponsors'
      fullPath: '/admin/sponsors'
      preLoaderRoute: typeof AdminSponsorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sponsor-content': {
      id: '/admin/sponsor-content'
      path: '/sponsor-content'
      fullPath: '/admin/sponsor-content'
      preLoaderRoute: typeof AdminSponsorContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/posts': {
      id: '/admin/posts'
      path: '/posts'
      fullPath: '/admin/posts'
      preLoaderRoute: typeof AdminPostsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/panelists': {
      id: '/admin/panelists'
      path: '/panelists'
      fullPath: '/admin/panelists'
      preLoaderRoute: typeof AdminPanelistsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/invitations': {
      id: '/admin/invitations'
      path: '/invitations'
      fullPath: '/admin/invitations'
      preLoaderRoute: typeof AdminInvitationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/founders': {
      id: '/admin/founders'
      path: '/founders'
      fullPath: '/admin/founders'
      preLoaderRoute: typeof AdminFoundersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/episodes': {
      id: '/admin/episodes'
      path: '/episodes'
      fullPath: '/admin/episodes'
      preLoaderRoute: typeof AdminEpisodesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/applications': {
      id: '/admin/applications'
      path: '/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AdminApplicationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminApplicationsRoute: typeof AdminApplicationsRoute
  AdminEpisodesRoute: typeof AdminEpisodesRoute
  AdminFoundersRoute: typeof AdminFoundersRoute
  AdminInvitationsRoute: typeof AdminInvitationsRoute
  AdminPanelistsRoute: typeof AdminPanelistsRoute
  AdminPostsRoute: typeof AdminPostsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSponsorContentRoute: typeof AdminSponsorContentRoute
  AdminSponsorsRoute: typeof AdminSponsorsRoute
  AdminTicketsRoute: typeof AdminTicketsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminApplicationsRoute: AdminApplicationsRoute,
  AdminEpisodesRoute: AdminEpisodesRoute,
  AdminFoundersRoute: AdminFoundersRoute,
  AdminInvitationsRoute: AdminInvitationsRoute,
  AdminPanelistsRoute: AdminPanelistsRoute,
  AdminPostsRoute: AdminPostsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSponsorContentRoute: AdminSponsorContentRoute,
  AdminSponsorsRoute: AdminSponsorsRoute,
  AdminTicketsRoute: AdminTicketsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface EpisodesRouteChildren {
  EpisodesSlugRoute: typeof EpisodesSlugRoute
}

const EpisodesRouteChildren: EpisodesRouteChildren = {
  EpisodesSlugRoute: EpisodesSlugRoute,
}

const EpisodesRouteWithChildren = EpisodesRoute._addFileChildren(
  EpisodesRouteChildren,
)

interface FoundersRouteChildren {
  FoundersSlugRoute: typeof FoundersSlugRoute
}

const FoundersRouteChildren: FoundersRouteChildren = {
  FoundersSlugRoute: FoundersSlugRoute,
}

const FoundersRouteWithChildren = FoundersRoute._addFileChildren(
  FoundersRouteChildren,
)

interface LegalRouteChildren {
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalRefundsRoute: typeof LegalRefundsRoute
  LegalTermsRoute: typeof LegalTermsRoute
}

const LegalRouteChildren: LegalRouteChildren = {
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalRefundsRoute: LegalRefundsRoute,
  LegalTermsRoute: LegalTermsRoute,
}

const LegalRouteWithChildren = LegalRoute._addFileChildren(LegalRouteChildren)

interface PanelistsRouteChildren {
  PanelistsSlugRoute: typeof PanelistsSlugRoute
}

const PanelistsRouteChildren: PanelistsRouteChildren = {
  PanelistsSlugRoute: PanelistsSlugRoute,
}

const PanelistsRouteWithChildren = PanelistsRoute._addFileChildren(
  PanelistsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ApplyRoute: ApplyRoute,
  AuthRoute: AuthRoute,
  CommunityRoute: CommunityRoute,
  CreatorsRoute: CreatorsRoute,
  EpisodesRoute: EpisodesRouteWithChildren,
  FoundersRoute: FoundersRouteWithChildren,
  InvitePanelistRoute: InvitePanelistRoute,
  JoinRoute: JoinRoute,
  LegalRoute: LegalRouteWithChildren,
  PanelistsRoute: PanelistsRouteWithChildren,
  PartnersRoute: PartnersRoute,
  PressKitRoute: PressKitRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SponsorsRoute: SponsorsRoute,
  TicketsRoute: TicketsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
